version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5 
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin 
      - KEYCLOAK_ADMIN_PASSWORD=admin123 
      - KC_DB=postgres 
      - KC_DB_URL_HOST=postgres 
      - KC_DB_URL_DATABASE=keycloak 
      - KC_DB_USERNAME=keycloak 
      - KC_DB_PASSWORD=keycloak123 
      - KC_HOSTNAME=localhost 
    ports:
      - "8080:8080" 
    depends_on:
      - postgres
    command: ["start-dev"]

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak123
    ports:
      - "5432:5432" 
